  File "password-evolution.py", line 8
    db name = 'prueba3.db'
       ^
SyntaxError: invalid syntax
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:9500/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Jun/2023 19:35:44] "[37mGET / HTTP/1.1[0m" 200 -

 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:9500/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Jun/2023 20:09:11] "[37mGET / HTTP/1.1[0m" 200 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:9500/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Jun/2023 20:34:00] "[33mPOST /singup/v1 HTTP/1.1[0m" 404 -
127.0.0.1 - - [21/Jun/2023 20:36:26] "[33mPOST /singup/v1 HTTP/1.1[0m" 404 -
127.0.0.1 - - [21/Jun/2023 20:38:05] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 20:38:14] "[33mPOST /singup/v1 HTTP/1.1[0m" 404 -
127.0.0.1 - - [21/Jun/2023 20:38:50] "[33mPOST /singup/v1 HTTP/1.1[0m" 404 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "password-evolution.py", line 56, in <module>
    app.run(host='0.0.0.0' , port=9500, ssl_context='adhoc')
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [21/Jun/2023 20:40:23] "[33mPOST /singup/v1 HTTP/1.1[0m" 404 -
[2023-06-21 20:41:36,907] ERROR in app: Exception on /signup/v1 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 19, in signup_v1
    c.execute('''TENEMOS QUE CREAR UNA TABLA EN CASO DE NO EXISTIR USER_PLAIN
sqlite3.OperationalError: near "TENEMOS": syntax error
127.0.0.1 - - [21/Jun/2023 20:41:36] "[35m[1mPOST /signup/v1 HTTP/1.1[0m" 500 -
[2023-06-21 20:42:25,250] ERROR in app: Exception on /signup/v1 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 19, in signup_v1
    c.execute('''TENEMOS QUE CREAR UNA TABLA EN CASO DE NO EXISTIR USER_PLAIN
sqlite3.OperationalError: near "TENEMOS": syntax error
127.0.0.1 - - [21/Jun/2023 20:42:25] "[35m[1mPOST /signup/v1 HTTP/1.1[0m" 500 -
[2023-06-21 20:46:17,766] ERROR in app: Exception on /signup/v1 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 19, in signup_v1
    c.execute('''''CREATE TABLE IF NOT EXISTS USER_PLAIN
sqlite3.OperationalError: near "TENEMOS": syntax error
127.0.0.1 - - [21/Jun/2023 20:46:17] "[35m[1mPOST /signup/v1 HTTP/1.1[0m" 500 -
[2023-06-21 20:47:49,207] ERROR in app: Exception on /signup/v1 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 19, in signup_v1
    c.execute('''CREATE TABLE IF NOT EXISTS USER_PLAIN
sqlite3.OperationalError: near "TENEMOS": syntax error
127.0.0.1 - - [21/Jun/2023 20:47:49] "[35m[1mPOST /signup/v1 HTTP/1.1[0m" 500 -
[2023-06-21 20:47:50,896] ERROR in app: Exception on /signup/v1 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 19, in signup_v1
    c.execute('''CREATE TABLE IF NOT EXISTS USER_PLAIN
sqlite3.OperationalError: near "TENEMOS": syntax error
127.0.0.1 - - [21/Jun/2023 20:47:50] "[35m[1mPOST /signup/v1 HTTP/1.1[0m" 500 -
[2023-06-21 20:49:55,995] ERROR in app: Exception on /signup/v1 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 19, in signup_v1
    c.execute('''CREATE TABLE IF NOT EXISTS USER_PLAIN
sqlite3.OperationalError: near "TENEMOS": syntax error
127.0.0.1 - - [21/Jun/2023 20:49:55] "[35m[1mPOST /signup/v1 HTTP/1.1[0m" 500 -
[2023-06-21 20:51:04,902] ERROR in app: Exception on /signup/v1 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 19, in signup_v1
    c.execute('''CREATE TABLE IF NOT EXISTS USER_PLAIN
sqlite3.OperationalError: near "TENEMOS": syntax error
127.0.0.1 - - [21/Jun/2023 20:51:04] "[35m[1mPOST /signup/v1 HTTP/1.1[0m" 500 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:9500/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Jun/2023 20:54:44] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 21:00:22] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 21:01:35] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 21:01:49] "[37mPOST /login/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 21:02:04] "[37mPOST /login/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 21:23:23] "[33mPOST /signup/v2 HTTP/1.1[0m" 404 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:9500/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Jun/2023 21:25:42] "[37mPOST /signup/v2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 21:25:54] "[37mPOST /login/v2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 21:30:35] "[37mPOST /signup/v2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [21/Jun/2023 21:30:47] "[37mPOST /login/v2 HTTP/1.1[0m" 200 -
